### PR TITLE
Coin liquidity data

### PR DESCRIPTION
**Pull request by 86667**

### CODE REVIEW

**Comment by 86667** [comment]
@alexyjs PR [these](https://github.com/commerceblock/mercury-wallet/issues/176) changes into this PR please

**Comment by lawlawlaw** [comment]
./src/components/createStatecoin/createStatecoin.js
Syntax error: Unexpected token (42:52)

  40 |
  41 |         // Sort
> 42 |         if (props.settings.sort_by==="Liquidity") {)
     |                                                    ^
  43 |           liquidity_data.sort((a,b) => {
  44 |             return b.liquidity - a.liquidity;
  45 |           })

**Comment by alexyjs** [comment]
Currently we have maximum 11 items, that's why there are only 11 items even we choose 12 option. 
And after the update there is only 10 items, because I set the smallest value is 0.000001, and we have one item value = 0.

**Comment by 86667** [comment]
There is in issue with the sorting here. If you change to sort by amount then go back to liquidity it sorts incorrectly.

**Pull request closed without merging**
